name: Visual Regression Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # Add caching for better performance
          cache: 'npm'

      # Add this step before npm ci
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Replace npm ci with pnpm install
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps webkit

      - name: Run Playwright tests with Pixeleye
        run: npx playwright test
        env:
          PIXELEYE_TOKEN: ${{ secrets.PIXELEYE_TOKEN }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30