name: "Pixeleye"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  pixeleye:
    runs-on: ubuntu-latest
    env:
      PIXELEYE_TOKEN: ${{ secrets.PIXELEYE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps webkit

      - name: Run Playwright tests with Pixeleye
        run: npm run test:e2e